apiVersion: v1

kind: ConfigMap

metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}

data:
  DB_HOST: "{{ .Values.backend.env.DB_HOST }}"
  DB_USER: "{{ .Values.backend.env.DB_USER }}"
  DB_NAME: "{{ .Values.backend.env.DB_NAME }}"